server:
  port: 8097

spring:
  application:
    name: scheduler

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka